dist: trusty
language: cpp

addons:
    apt:
        packages:
        - build-essential
        - python-yaml
        - ruby
        - libzmq3-dev
        - libzmqpp-dev
        - libgtest-dev
        - libgflags-dev gcovr

matrix:
    include:
        - name: Coverage build
          env: CONFFLAGS="--enable-gcov"
        - name: ASAN build
          env: CONFFLAGS="--enable-asan"
        - name: MSAN build
          env: CONFFLAGS="--enable-msan"

# Setup stechec2 with prologin2018
install:
    - git clone https://github.com/prologin/stechec2.git
    - cd stechec2
    - git clone https://github.com/prologin/prologin2018.git games/prologin2018
    - echo $CONFFLAGS
    - ( ./waf.py configure --with-games=prologin2018 $CONFFLAGS ) || ( cat /home/travis/build/prologinsandbox/prologin2018/stechec2/build/config.log )

script:
    - ./waf.py build
    - ./waf.py build --check
    - ./waf.py coverage
