dist: xenial
language: cpp

addons:
    apt:
        packages:
        - build-essential
        - python-yaml
        - ruby
        - libzmq3-dev
        - libzmqpp-dev
        - libgtest-dev
        - libgflags-dev gcovr

matrix:
    include:
        - name: Normal build
          env: SANFLAGS=
        - name: ASAN build
          env: SANFLAGS="--enable-asan"
        - name: MSAN build
          env: SANFLAGS="--enable-msan"


# Setup stechec2 with prologin2018
install:
    - git clone https://github.com/prologin/stechec2.git
    - cd stechec2
    - git clone https://github.com/prologin/prologin2018.git games/prologin2018
    - echo $SANFLAGS
    - ./waf.py configure --with-games=prologin2018 --enable-gcov $SANFLAGS

script:
    - ./waf.py build
    - ./waf.py build --check
    - ./waf.py coverage
