dist: xenial
language: cpp

addons:
    apt:
        packages:
            # stechec2 dependencies
            - build-essential python3-yaml ruby
            - libzmq3-dev libzmqpp-dev libgtest-dev libgflags-dev gcovr

matrix:
    include:
        - name: GCC build
          env: CONFFLAGS=
          compiler: gcc

        - name: Clang build
          env: CONFFLAGS=
          compiler: clang

        - name: Coverage build
          env: CONFFLAGS="--enable-gcov"
          compiler: gcc

        - name: ASAN build
          env: CONFFLAGS="--enable-asan"
          compiler: clang

        - name: MSAN build
          env: CONFFLAGS="--enable-msan"
          compiler: clang

install:
    # Setup stechec2 with prologin2018
    - git clone https://github.com/prologin/stechec2
    - cd stechec2
    - git clone https://github.com/prologin/prologin2018 games/prologin2018
    - ( ./waf.py configure --with-games=prologin2018 $CONFFLAGS ) || \
      ( cat ./build/config.log )

script:
    - ./waf.py build --check
    - ./waf.py coverage
