dist: xenial
language: cpp

addons:
    apt:
        packages:
        - build-essential
        - python-yaml
        - ruby
        - libzmq3-dev
        - libzmqpp-dev
        - libgtest-dev
        - libgflags-dev gcovr

# Setup stechec2 with prologin2018
install:
    - git clone https://github.com/prologin/stechec2.git
    - cd stechec2
    - git clone https://github.com/prologin/prologin2018.git games/prologin2018
    - (./waf.py configure --with-games=prologin2018 --enable-gcov --enable-asan --verbose) || (cat /home/travis/build/prologinsandbox/prologin2018/stechec2/build/config.log)

script:
    - ./waf.py build

after_success:
    - ./waf.py build --check
    - ./waf.py coverage
