language: cpp
compiler: gcc

# Setup stechec2 with prologin2018
install:
    - apt-get install build-essential python-yaml ruby
    - apt-get install libzmq3-dev libzmqpp-dev libgtest-dev libgflags-dev gcovr
    - git clone https://github.com/prologin/stechec2.git
    - cd stechec2
    - git clone https://github.com/prologin/prologin2018.git games/prologin2018
    - ./waf.py configure --with-games=prologin2018 --enable-gcov --enable-asan

script:
    - ./waf.py build

after_success:
    - ./waf.py build --check
    - ./waf.py coverage
